---
on:
  pull_request: 
    types: ['created'] 
    branches: ['main']
jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: bash-version
        run: echo "::add-mask::$MY_NAME"
